services:
    db:
        image: postgres:latest
        restart: unless-stopped
        container_name: template_db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DATABASE: ${DB_DATABASE}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s

    keycloak:
        image: keycloak/keycloak
        restart: unless-stopped
        container_name: template_keycloak
        ports:
            - "8080:8080"
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
        command:
            - start-dev
